
  export const movies = [
  {
    id: 1,
    title: "Cosmic Odyssey",
    genre: "Sci-Fi",
    year: 2024,
    rating: 8.5,
    duration: "2h 15m",
    poster: "/images/cosmic-odyssey-poster.png",
    backdrop: "/images/cosmic-odyssey-backdrop.png",
    description:
      "An epic journey through space and time as humanity discovers ancient alien technology that could change the fate of civilization forever.",
    featured: true,
    trending: true,
    popular: true,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Alex Johnson", "Sarah Chen", "Michael Torres"],
    director: "Emma Rodriguez",
  },
  {
    id: 2,
    title: "Shadow Detective",
    genre: "Thriller",
    year: 2023,
    rating: 7.8,
    duration: "1h 45m",
    poster: "/images/arctic-storm-poster.png",
    backdrop: "/images/arctic-storm-backdrop.png",
    description:
      "A detective uncovers a conspiracy that goes deeper than anyone imagined in this gripping psychological thriller.",
    trending: true,
    popular: false,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["David Kim", "Lisa Wang", "Robert Brown"],
    director: "James Wilson",
  },
  {
    id: 3,
    title: "Dragon's Legacy",
    genre: "Fantasy",
    year: 2024,
    rating: 9.1,
    duration: "2h 30m",
    poster: "/images/dragon-legacy-poster.png",
    backdrop: "/images/dragon-legacy-backdrop.png",
    description: "The last dragon rider must save the kingdom from an ancient evil in this breathtaking fantasy epic.",
    trending: true,
    popular: true,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    cast: ["Emma Stone", "Chris Hemsworth", "Benedict Cumberbatch"],
    director: "Peter Jackson",
  },
  {
    id: 4,
    title: "City Lights",
    genre: "Romance",
    year: 2023,
    rating: 7.2,
    duration: "1h 55m",
    poster: "/images/city-lights-poster.png",
    backdrop: "/images/city-lights-backdrop.png",
    description:
      "Two strangers meet in the bustling streets of New York and find unexpected love in this heartwarming romance.",
    trending: false,
    popular: true,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    cast: ["Ryan Gosling", "Emma Stone", "John Krasinski"],
    director: "Damien Chazelle",
  },
  {
    id: 5,
    title: "The Heist",
    genre: "Action",
    year: 2024,
    rating: 8.0,
    duration: "2h 5m",
    poster: "/images/ocean-depths-poster.jpg",
    backdrop: "/images/ocean-depths-backdrop.webp",
    description:
      "A master thief plans the ultimate heist that could change everything in this high-octane action thriller.",
    trending: false,
    popular: true,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    cast: ["Tom Cruise", "Charlize Theron", "Idris Elba"],
    director: "Christopher McQuarrie",
  },
  {
    id: 6,
    title: "Quantum Realm",
    genre: "Sci-Fi",
    year: 2023,
    rating: 8.7,
    duration: "2h 20m",
    poster: "/images/quantum-realm-poster.png",
    backdrop: "/images/quantum-realm-backdrop.png",
    description:
      "Scientists discover a parallel universe with dangerous consequences in this mind-bending sci-fi adventure.",
    trending: true,
    popular: true,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    cast: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas"],
    director: "Peyton Reed",
  },
  {
    id: 7,
    title: "Midnight Runner",
    genre: "Action",
    year: 2024,
    rating: 7.5,
    duration: "1h 50m",
    poster: "/images/midnight-runner-poster.png",
    backdrop: "/images/midnight-runner-backdrop.png",
    description:
      "A street racer gets caught up in a dangerous underground world in this adrenaline-fueled action film.",
    trending: false,
    popular: false,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    cast: ["Vin Diesel", "Michelle Rodriguez", "Tyrese Gibson"],
    director: "Justin Lin",
  },
  {
    id: 8,
    title: "Ocean Depths",
    genre: "Adventure",
    year: 2023,
    rating: 8.3,
    duration: "2h 10m",
    poster: "/images/ocean-depths-poster.jpg",
    backdrop: "/images/ocean-depths-backdrop.webp",
    description:
      "Deep sea explorers discover ancient secrets beneath the ocean in this thrilling underwater adventure.",
    trending: false,
    popular: true,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    cast: ["Jason Statham", "Li Bingbing", "Rainn Wilson"],
    director: "Jon Turteltaub",
  },
  {
    id: 9,
    title: "Neon Nights",
    genre: "Thriller",
    year: 2024,
    rating: 7.9,
    duration: "1h 58m",
    poster: "/images/neon-nights-poster.webp",
    backdrop: "/images/neon-nights-backdrop.webp",
    description: "In a neon-lit city, a private investigator gets caught in a web of corruption and betrayal.",
    trending: true,
    popular: false,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    cast: ["Ryan Reynolds", "Scarlett Johansson", "Oscar Isaac"],
    director: "Denis Villeneuve",
  },
  {
    id: 10,
    title: "Arctic Storm",
    genre: "Adventure",
    year: 2023,
    rating: 7.6,
    duration: "2h 8m",
    poster: "/images/arctic-storm-poster.png",
    backdrop: "/images/arctic-storm-backdrop.png",
    description: "A team of researchers must survive in the harsh Arctic wilderness after their expedition goes wrong.",
    trending: false,
    popular: true,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Jake Gyllenhaal", "Tilda Swinton", "John Turturro"],
    director: "Alejandro G. Iñárritu",
  },
  {
    id: 11,
    title: "Love Story",
    genre: "Romance",
    year: 2024,
    rating: 8.1,
    duration: "1h 42m",
    poster: "/images/love-story-poster.png",
    backdrop: "/images/love-story-backdrop.png",
    description: "A timeless tale of love that transcends all boundaries in this beautifully crafted romantic drama.",
    trending: false,
    popular: true,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    cast: ["Timothée Chalamet", "Saoirse Ronan", "Laura Dern"],
    director: "Greta Gerwig",
  },
  {
    id: 12,
    title: "Space Wars",
    genre: "Sci-Fi",
    year: 2024,
    rating: 8.8,
    duration: "2h 35m",
    poster: "/images/space-wars-poster.jpg",
    backdrop: "/images/space-wars-backdrop.jpg",
    description: "An intergalactic war threatens the universe as rebels fight against an evil empire.",
    trending: true,
    popular: true,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    cast: ["Oscar Isaac", "Daisy Ridley", "John Boyega"],
    director: "Rian Johnson",
  },
  {
    id: 13,
    title: "Mystery Island",
    genre: "Adventure",
    year: 2023,
    rating: 7.4,
    duration: "1h 52m",
    poster: "/images/mystery-island-poster.png",
    backdrop: "/images/mystery-island-backdrop.png",
    description: "Explorers discover a mysterious island with secrets that could change everything they know.",
    trending: false,
    popular: false,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    cast: ["Tom Holland", "Zendaya", "Mark Wahlberg"],
    director: "Ruben Fleischer",
  },
  {
    id: 14,
    title: "Cyber Punk",
    genre: "Sci-Fi",
    year: 2024,
    rating: 8.2,
    duration: "2h 12m",
    poster: "/images/cyber-punk-backdrop.jpg",
    backdrop: "/images/cyber-punk-backdrop.jpg",
    description: "In a dystopian future, a hacker fights against corporate control in this cyberpunk thriller.",
    trending: true,
    popular: true,
    newRelease: true,
    videoUrl: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
    cast: ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne"],
    director: "Lana Wachowski",
  },
  {
    id: 15,
    title: "Dark Knight Returns",
    genre: "Action",
    year: 2023,
    rating: 8.9,
    duration: "2h 28m",
   poster: "/images/v2.jpg",
    backdrop: "/images/v2.jpg",
    description: "The legendary hero returns to face his greatest challenge yet in this epic action adventure.",
    trending: true,
    popular: true,
    newRelease: false,
    videoUrl: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    cast: ["Christian Bale", "Gary Oldman", "Anne Hathaway"],
    director: "Christopher Nolan",
  },
  {
    id: 16,
    title: "Enchanted Forest",
    genre: "Fantasy",
    year: 2024,
    rating: 7.7,
    duration: "1h 48m",
    poster: "/images/enchanted-forest-poster.jpg",
    backdrop: "/images/enchanted-forest-backdrop.jpg",
    description: "A magical journey through an enchanted forest where mythical creatures come to life.",
    trending: false,
    popular: true,
    newRelease: true,
    videoUrl: "https://filesamples.com/samples/video/mp4/SampleVideo_1280x720_1mb.mp4",
    cast: ["Amy Adams", "Patrick Dempsey", "James Marsden"],
    director: "Kevin Lima",
  },
  {
    id: 17,
    title: "Heart of Gold",
    genre: "Romance",
    year: 2023,
    rating: 7.3,
    duration: "1h 56m",
    poster: "/images/heart-of-gold-poster.jpg",
    backdrop: "/images/heart-of-gold-backdrop.jpg",
    description: "A touching story about finding love in the most unexpected places.",
    trending: false,
    popular: false,
    newRelease: false,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Hugh Jackman", "Michelle Williams", "Zac Efron"],
    director: "Michael Gracey",
  },
  {
    id: 18,
    title: "Silent Witness",
    genre: "Thriller",
    year: 2024,
    rating: 8.4,
    duration: "2h 3m",
    poster: "/images/silent-witness-poster.jpg",
    backdrop: "/images/silent-witness-backdrop.jpg",
    description: "A psychological thriller about a witness who holds the key to solving a murder case.",
    trending: true,
    popular: true,
    newRelease: true,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Joaquin Phoenix", "Amy Adams", "Philip Seymour Hoffman"],
    director: "Paul Thomas Anderson",
  },
]

export const genres = ["All", "Sci-Fi", "Thriller", "Fantasy", "Romance", "Action", "Adventure"]
